### ISSUE TITLE
PDO::prepare(): send of 136 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by jinand10** [RunnerLee/fastd-eloquent#5]
sql连接闲置一段时间，再次使用该连接的时候，会报这个错，试过吗？

**Comment by RunnerLee** [comment]
我尝试复现下，晚些给你回复。

**Comment by RunnerLee** [comment]
@jinand10 你好，感谢反馈，我这边重现的环境是：

php: 7.3.10
swoole: 4.4.7
mysql: 5.7.27

谷歌搜到的类似一个情况是：https://github.com/delight-im/PHP-DB/issues/5

```
Might the problem be related to this PHP issue? https://bugs.php.net/bug.php?id=53287 There, it is suggested to change the wait_timeout directive in the MySQL configuration.
```

我在本地通过设置 `my.cnf` 中 `wait_timeout=10` 来重现，取到的错误消息是：

```
PHP Warning:  PDO::query(): MySQL server has gone away
```

这个错误消息是能被 eloquent 捕获并进行重连的，那么也有可能是开启了 `persistent` 的原因，但不确定你使用的是我这个包还是 zqhong 的这个包 https://github.com/zqhong/fastd-eloquent. 因为我这个包没支持自定义参数。

但无论是哪种情况都应该是超时才触发，所以建议在代码中自动重连。下面给出一个通过自定义 Server 来实现用定时器自动重启的例子：

```php
namespace Server;

use swoole_server;
use FastD\Servitization\Server\HTTPServer;

class Http extends HTTPServer
{
    public function onWorkerStart(swoole_server $server, $worker_id)
    {
        parent::onWorkerStart($server, $worker_id);

        $timeout = eloquent_db()->selectOne("SHOW VARIABLES LIKE 'wait_timeout'")->Value;
        $timeout = max((int) $timeout, 1);

        swoole_timer_tick($timeout * 1000, function () {
            foreach (app()->get('eloquent')->getDatabaseManager()->getConnections() as $connection) {
                $connection->reconnect();
            }
        });
    }
}
```

**Comment by marlonfan** [comment]
@RunnerLee @jinand10 这里的 errno=32 是socket抛出的错误,在linux的socket编程中,出现这个错误有两种可能性

```
1.socket失败，与服务器端的链接没有成功，从而管道破裂。
2.服务端将客户端的socket断开，一样造成这样的问题。
```

这里因为没有做一个连接池的有效检测,所以可能拿到的mysql链接已经是断开的, 而PHP并不知道,继续往这个socket管道里面写东西就会超时、错误.

我之前参考过 hyperf 的实现, 他们的 check 检查连接直接是根据 最大空闲时间 来实现的, reconnect操作直接把数据库链接新建一个覆盖. 

- [重连代码](https://github.com/hyperf-cloud/db-connection/blob/master/src/Connection.php#L85)
- [检查连接可用代码](https://github.com/hyperf-cloud/pool/blob/master/src/Connection.php#L51)

- 这是我当时和他们的讨论 [issue 141](https://github.com/hyperf-cloud/hyperf/issues/141)

争论下来,我觉得目前使用最大空闲时间确实是一个比较好的做法,参照他们的 check 方法.

**Comment by RunnerLee** [comment]
@marlonfan 搜了一下 `Broken pipe`，大致意思是由于 SIGPIPE 引起的
```
# FROM: https://www.gnu.org/software/libc/manual/html_mono/libc.html#Error-Codes

“Broken pipe.” There is no process reading from the other end of a pipe. Every library function that returns this error code also generates a SIGPIPE signal; this signal terminates the program if not handled or blocked. Thus, your program will never actually see EPIPE unless it has handled or blocked SIGPIPE.
```

触发的原因可能是管道的一端已经断开连接或者关闭读写，在这个问题里我猜应该是 mysql 已经断开连接但 PDO 没处理好 （瞎猜的..），如果的确是这样的话，直接重连就好了。

至于重连的机制我觉得怎样都好，像 hyperf 的实现是每次调用 `getActiveConnection()` 或是直接调用 `check()` 来更新最后活跃时间，也是要设置一个最大 idle 时间。

因为是用的 swoole，我觉得最省时省力的方式还是通过定时器来解决就好。

或者 @jinand10 能否提供下更多的信息，包括 php / mysql / swoole 的版本。

**Comment by jinand10** [comment]
如果是在process中进行 eloquent的DB操作呢? 消费进程中距上一次DB连接闲置太久了，再次消费的时候也会报这种错

**Comment by RunnerLee** [comment]
@jinand10 还得在 process 中再加一个定时器.. 暂时只能想到这个笨方法

**Comment by RunnerLee** [comment]
> @jinand10 还得在 process 中再加一个定时器.. 暂时只能想到这个笨方法

抱歉我沙雕了，如果是 mq 消费者进程就不能用定时器了，需要在每消费一条消息之前检查连接存活，方便一点也可以用最大空闲时间的方式。

**Comment by RunnerLee** [comment]
> @jinand10 还得在 process 中再加一个定时器.. 暂时只能想到这个笨方法

@jinand10 抱歉我沙雕了，如果是 mq 消费者进程就不能用定时器了，需要在每消费一条消息之前检查连接状态，方便一点也可以用最大空闲时间的方式。

**Comment by RunnerLee** [comment]
重新整理了下，首先希望能确定 `Broken pipe` 的产生原因，我更倾向于可能是 php / mysql 的问题，目前猜测的应该就是超时，所以就需要针对这种特殊情况做重连。

至于重连，可以试试直接改造 laravel 的重连机制：

新增一个 Connection
```php
namespace Services;

use Closure;
use PDOException;
use Illuminate\Database\QueryException;
use Illuminate\Database\MySqlConnection as BaseConnection;

class MysqlConnection extends BaseConnection
{
    protected function tryAgainIfCausedByLostConnection(QueryException $e, $query, $bindings, Closure $callback)
    {
        try {
            return parent::tryAgainIfCausedByLostConnection(
                $e,
                $query,
                $bindings,
                $callback
            );
        } catch (PDOException $exception) {
            if (false !== strpos($exception->getMessage(), 'errno=32 Broken pipe')) {
                $this->reconnect();
                return $this->runQueryCallback($query, $bindings, $callback);
            }

            throw $exception;
        }
    }
}
```

然后注册

```php
        Connection::resolverFor('mysql', function ($connection, $database, $prefix, $config) {
            return new MysqlConnection($connection, $database, $prefix, $config);
        });
```

这样就可以了。我就先不在这个包里面加，因为我还没找到复现的方法。

**Comment by RunnerLee** [comment]
另外，定时器的方式也是沙雕方式。建议还是用改造重连机制的方式

**Comment by KevinHubs** [comment]
同样遇到这个问题,我直接在脚本里 做时间间隔检测 规定时间重启进程了,还在观察中

**Comment by KevinHubs** [comment]
同样遇到这个问题,我直接在脚本里 做时间间隔检测 规定时间重启进程了,还在观察中

**Comment by KevinHubs** [comment]
同样遇到这个问题,我直接在脚本里 做时间间隔检测 规定时间重启进程了,还在观察中
